### ISSUE TITLE
API Playground not working

### ISSUE THREAD

**Issue by mugavri** [tjhorner/schema.tl#29]
API Playground  on https://tjhorner.com/webogram not working

**Comment by tjhorner** [comment]
try here: https://tjhorner.dev/webogram

I will update the link eventually

**Comment by mugavri** [comment]
> try here: https://tjhorner.dev/webogram
> 
> I will update the link eventually

tanks, but its not updated to last layer 111

**Comment by tjhorner** [comment]
I probably won't update it to 111. You can submit a PR to tjhorner/webogram if you want.
