### ISSUE TITLE
update to api layer 117

### ISSUE THREAD

**Issue by mugavri** [tjhorner/schema.tl#38]
https://github.com/telegramdesktop/tdesktop/commit/4bf6550e24e46a2d8cab06b533a7e26e0d7da685

**Comment by tjhorner** [comment]
Hmm, looks like I will need to update the bot to take into account schemas from other branches. Right now [it only checks `master`](https://github.com/tjhorner/schema.tl/blob/e067b8152824872a7e0b1750c52748876ea10af7/tools/update-schema/index.js#L54). This also raises the question: is this version of Layer 117 final? I will ask the TDesktop dev to see if it can scan the branches and be sure that any newer schema it finds is final.

**Comment by tjhorner** [comment]
The bot picked it up since it's now in master; added in #39
